<?php
return array (
  53 => 
  array (
    'typeid' => '53',
    'siteid' => '1',
    'module' => 'content',
    'modelid' => '0',
    'name' => '评测',
    'parentid' => '0',
    'typedir' => '',
    'url' => '',
    'template' => '',
    'listorder' => '0',
    'description' => '',
  ),
  54 => 
  array (
    'typeid' => '54',
    'siteid' => '1',
    'module' => 'content',
    'modelid' => '0',
    'name' => '资讯',
    'parentid' => '0',
    'typedir' => '',
    'url' => '',
    'template' => '',
    'listorder' => '0',
    'description' => '',
  ),
  55 => 
  array (
    'typeid' => '55',
    'siteid' => '1',
    'module' => 'content',
    'modelid' => '0',
    'name' => '观点',
    'parentid' => '0',
    'typedir' => '',
    'url' => '',
    'template' => '',
    'listorder' => '0',
    'description' => '',
  ),
  56 => 
  array (
    'typeid' => '56',
    'siteid' => '1',
    'module' => 'content',
    'modelid' => '0',
    'name' => '专访',
    'parentid' => '0',
    'typedir' => '',
    'url' => '',
    'template' => '',
    'listorder' => '0',
    'description' => '',
  ),
  57 => 
  array (
    'typeid' => '57',
    'siteid' => '1',
    'module' => 'content',
    'modelid' => '0',
    'name' => '厂商稿',
    'parentid' => '0',
    'typedir' => '',
    'url' => '',
    'template' => '',
    'listorder' => '0',
    'description' => '',
  ),
  58 => 
  array (
    'typeid' => '58',
    'siteid' => '1',
    'module' => 'content',
    'modelid' => '0',
    'name' => '专题',
    'parentid' => '0',
    'typedir' => '',
    'url' => '',
    'template' => '',
    'listorder' => '0',
    'description' => '',
  ),
  59 => 
  array (
    'typeid' => '59',
    'siteid' => '1',
    'module' => 'content',
    'modelid' => '0',
    'name' => '视频',
    'parentid' => '0',
    'typedir' => '',
    'url' => '',
    'template' => '',
    'listorder' => '0',
    'description' => '',
  ),
  60 => 
  array (
    'typeid' => '60',
    'siteid' => '1',
    'module' => 'content',
    'modelid' => '0',
    'name' => '今日爆款',
    'parentid' => '0',
    'typedir' => '',
    'url' => '',
    'template' => '',
    'listorder' => '0',
    'description' => '',
  ),
);
?>